stages:
  - build
  - format

### Build stage
#
# build the project and run its tests

build:
  stage: build

  image: yag000/dune-testing:latest

  script:
    - opam install . --deps-only --with-test --yes

    - eval $(opam env)

    - dune build

    - dune runtest

### Format stage
#
# format the project

format:
  stage: format

  image: yag000/dune-testing:latest

  script:
    - opam install . --deps-only --with-test --yes

    - eval $(opam env)

    - dune build @fmt --auto-promote

